### ISSUE TITLE
SSL_library_init: Failed to load Electron preload script

### ISSUE THREAD

**Issue by curVV** [iotaledger/trinity-wallet#2162]
Since around 0.5.0+, I think, I am unable to run Trinity from local build.
Build and compile finish without error.
But I get the following when run:
```
Failed to load Electron preload script
{"error":"Error: /tmp/.org.chromium.Chromium.wA2y5V: undefined symbol: SSL_library_init
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_trinitq9p1y0/resources/app.asar/node_modules/realm/lib/index.js:103:28)
    at Object.<anonymous> (/tmp/.mount_trinitq9p1y0/resources/app.asar/node_modules/realm/lib/index.js:139:3)"}
```
As far as I know SSL_library_init is a symbol of older openssl. Which openssl version is the release of Trinity built against?

My system is Gentoo and I have also tried on Artix (Arch) with the same results. Both using openssl-1.1.1c-r1.

**Comment by rajivshah3** [comment]
Hi, can you please fill out the bug report template? It includes questions about OS information which would help us investigate this issue.

**Comment by curVV** [comment]
Just built 1.1.0. No issues.

**Comment by rajivshah3** [comment]
@curVV so the issue is resolved?
