### ISSUE TITLE
Crash on launch when running Android 5.0

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#2337]
### Bug description
Crashes on Android 5.0 (API level 21) are occurring with messages similar to #1135 and #1463. According to Google Play, this crash has occurred since build 83, but it's possible that this issue occurred before that.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Huawei (Firebase Test Lab)
- Model: P8 Lite (ALE-L23)
- OS version: Android 5.0.1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v1.2.0 (89)

### Steps To Reproduce
1. Open Trinity on a device running Android 5.0

### Expected behaviour
App should not crash

### Actual behaviour
App crashes on launch

### Errors
```
09-25 14:29:19.978: E/art(17996): dlopen("/data/app/com.iota.trinity-1/lib/arm64/libdummy.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/com.iota.trinity-1/lib/arm64/libdummy.so"...
09-25 14:29:19.978: E/AndroidRuntime(17996): FATAL EXCEPTION: main
09-25 14:29:19.978: E/AndroidRuntime(17996): Process: com.iota.trinity, PID: 17996
09-25 14:29:19.978: E/AndroidRuntime(17996): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/com.iota.trinity-1/lib/arm64/libdummy.so"...
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at java.lang.Runtime.loadLibrary(Runtime.java:383)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at java.lang.System.loadLibrary(System.java:998)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at com.iota.trinity.MainApplication.attachBaseContext(MainApplication.java:53)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.Application.attach(Application.java:187)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.Instrumentation.newApplication(Instrumentation.java:996)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.Instrumentation.newApplication(Instrumentation.java:980)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:582)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4766)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.ActivityThread.access$1900(ActivityThread.java:152)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.os.Looper.loop(Looper.java:135)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at android.app.ActivityThread.main(ActivityThread.java:5538)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at java.lang.reflect.Method.invoke(Native Method)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at java.lang.reflect.Method.invoke(Method.java:372)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
09-25 14:29:19.978: E/AndroidRuntime(17996): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by rajivshah3** [comment]
Relevant issue: https://github.com/android/ndk/issues/964

Relevant NDK documentation: https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#available-in-api-level-23

Linking against `libta` is a possible [workaround](https://talk.sonymobile.com/t5/Android-5-x-Lollipop/Compilation-problem-undefined-reference-to-dlopen/m-p/1285691/highlight/true#M362)

**Comment by cvarley100** [comment]
@rajivshah3 Are these logs from Bugsnag?
