### ISSUE TITLE
Missing security dependencies on Void Linux

### ISSUE THREAD

**Issue by gspe** [iotaledger/trinity-wallet#464]
### Bug description
I have Trinity Wallet Appimage on Void Linux but it doesn't start.
I have ```libsecret``` and ```gnome-keyring``` installed and started

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Dell
- Model: 
- OS version: Void Linux x86_64 kernel 4.18.11_1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: trinity-desktop-0.3.6.AppImage

### Expected behaviour
The app should run.

### Actual behaviour
tuck at a screen telling me to install missing dependencies

### Errors
Running from terminal ```./trinity-desktop-0.3.6.AppImage``` doesn't show any related error 
How do you check if libsecret is installed?

**Comment by rajivshah3** [comment]
There might be more detailed messages if you add the following:
`console.log(err)`
above this line:
https://github.com/iotaledger/trinity-wallet/blob/develop/src/desktop/src/ui/Index.js#L171

You can then run the development version of Trinity by cloning this repo and running `yarn && cd src/shared && yarn && cd ../desktop && npm install && npm run start`

**Comment by gspe** [comment]
I did what you ask but it still doesn't work and I can't see any new error messages.

**Comment by rajivshah3** [comment]
Have you checked the debugger? When you run `npm run start` it should show a window that looks like the Chrome debugger. If you click on the `Console` tab it should show these messages

**Comment by gspe** [comment]
My fault, I've recompiled and when I run ```npm start```  it just crash with this error messages:
```
npm start

> trinity-desktop@0.3.6 start /home/gspe/Dev/trinity-wallet/src/desktop
> concurrently --kill-others "npm run devserver" "cross-env NODE_ENV=development electron main.js"

[1] 
[1] (electron:12900): Gtk-WARNING **: 10:35:35.670: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
[1] 
[1] (electron:12900): Gtk-WARNING **: 10:35:35.670: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
[1] 
[1] (electron:12900): Gtk-WARNING **: 10:35:35.670: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[0] 
[0] > trinity-desktop@0.3.6 devserver /home/gspe/Dev/trinity-wallet/src/desktop
[0] > node server.js
[0] 
[1] (node:12900) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawn unzip ENOENT
[1] (node:12900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] (node:12900) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: spawn unzip ENOENT
[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE :::1074
[0]     at Object._errnoException (util.js:992:11)
[0]     at _exceptionWithHostPort (util.js:1014:20)
[0]     at Server.setupListenHandle [as _listen2] (net.js:1355:14)
[0]     at listenInCluster (net.js:1396:12)
[0]     at Server.listen (net.js:1480:7)
[0]     at Function.listen (/home/gspe/Dev/trinity-wallet/src/desktop/node_modules/express/lib/application.js:618:24)
[0]     at Object.<anonymous> (/home/gspe/Dev/trinity-wallet/src/desktop/server.js:32:5)
[0]     at Module._compile (module.js:652:30)
[0]     at Object.Module._extensions..js (module.js:663:10)
[0]     at Module.load (module.js:565:32)
[0]     at tryModuleLoad (module.js:505:12)
[0]     at Function.Module._load (module.js:497:3)
[0]     at Function.Module.runMain (module.js:693:10)
[0]     at startup (bootstrap_node.js:191:16)
[0]     at bootstrap_node.js:612:3
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! trinity-desktop@0.3.6 devserver: `node server.js`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the trinity-desktop@0.3.6 devserver script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/gspe/.npm/_logs/2018-10-10T08_35_36_628Z-debug.log
[0] npm run devserver exited with code 1
--> Sending SIGTERM to other processes..
[1] cross-env NODE_ENV=development electron main.js exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trinity-desktop@0.3.6 start: `concurrently --kill-others "npm run devserver" "cross-env NODE_ENV=development electron main.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trinity-desktop@0.3.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gspe/.npm/_logs/2018-10-10T08_35_36_747Z-debug.log
```

**Comment by rajivshah3** [comment]
> Error: listen EADDRINUSE :::1074

@gspe do you have anything running on port 1074?

**Comment by gspe** [comment]
Hi, I've rebooted and pulled last version now it seams to compile and run.
When I start it with ``` npm run start``` it start but the only thing I can see is a blue screen with the top menu, when I click the menu items nothing happens and nothing is printed in the chrome console.

It seams similar to #534 and #305 

After a minute or two this message is printed on shell:
```
npm run start

> trinity-desktop@0.3.6 start /home/gspe/Dev/trinity-wallet/src/desktop
> concurrently --kill-others "npm run devserver" "cross-env NODE_ENV=development electron main.js"

[0] 
[0] > trinity-desktop@0.3.6 devserver /home/gspe/Dev/trinity-wallet/src/desktop
[0] > node server.js
[0] 
[1] 
[1] (electron:4351): Gtk-WARNING **: 09:54:33.142: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version
[1] 
[1] (electron:4351): Gtk-WARNING **: 09:54:33.142: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version
[1] 
[1] (electron:4351): Gtk-WARNING **: 09:54:33.142: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[1] node[4351]: pthread_create: Invalid argument
[1] (electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
[1] (node:4351) UnhandledPromiseRejectionWarning: Error: spawn unzip ENOENT
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
[1]     at onErrorNT (internal/child_process.js:406:16)
[1]     at process._tickCallback (internal/process/next_tick.js:63:19)
[1] (node:4351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:4351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] (node:4351) UnhandledPromiseRejectionWarning: Error: spawn unzip ENOENT
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
[1]     at onErrorNT (internal/child_process.js:406:16)
[1]     at process._tickCallback (internal/process/next_tick.js:63:19)
[1] (node:4351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[0] => 🌎 http://localhost:1074/
[0] webpack built a72498b33a198eed5470 in 13089ms
[0] ⚠ ｢wdm｣: Hash: a72498b33a198eed5470
[0] Version: webpack 4.20.2
[0] Time: 13089ms
[0] Built at: 18/10/2018 09:54:47
[0]               Asset       Size  Chunks             Chunk Names
[0] images/f332af3e.svg    176 KiB          [emitted]  
[0] images/0cdb648a.ttf    117 KiB          [emitted]  
[0] images/5182da42.ttf    287 KiB          [emitted]  
[0] images/774c05cc.ttf    285 KiB          [emitted]  
[0] images/341296e6.ttf   20.1 KiB          [emitted]  
[0] images/71e0bedc.svg    150 KiB          [emitted]  
[0] images/ee2a11b8.ttf    286 KiB          [emitted]  
[0]           bundle.js   27.7 MiB    main  [emitted]  main
[0]          index.html  300 bytes          [emitted]  
[0]            icon.png   4.29 KiB          [emitted]  
[0] trayTemplate@2x.png   1.07 KiB          [emitted]  
[0]            icon.ico    110 KiB          [emitted]  
[0]           icon.icns    259 KiB          [emitted]  
[0] Entrypoint main = bundle.js
[0] [../shared/store.js] 1.74 KiB {main} [built]
[0] [./node_modules/bugsnag-js/dist/bugsnag.js] 670 KiB {main} [built]
[0] [./node_modules/bugsnag-react/dist/bugsnag-react.js] 3.87 KiB {main} [built]
[0] [./node_modules/lodash/get.js] 884 bytes {main} [built]
[0] [./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[0] [./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[0] [./node_modules/react-i18next/dist/es/index.js] 447 bytes {main} [built]
[0] [./node_modules/react-redux/es/index.js] 230 bytes {main} [built]
[0] [./node_modules/react-router/es/index.js] 723 bytes {main} [built]
[0] [./node_modules/react/index.js] 190 bytes {main} [built]
[0] [./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[0] [0] multi webpack-hot-middleware/client?reload=true ./src/index.js 40 bytes {main} [built]
[0] [./node_modules/webpack-hot-middleware/client.js?reload=true] (webpack)-hot-middleware/client.js?reload=true 7.59 KiB {main} [built]
[0] [./src/index.js] 1.94 KiB {main} [built]
[0] [./src/ui/global/Alerts.js] 1.48 KiB {main} [built]
[0]     + 1836 hidden modules
[0] 
[0] WARNING in ../shared/containers/global/Alerts.js 29:4-19
[0] "export 'disposeOffAlert' was not found in '../../actions/alerts'
[0]  @ ./src/ui/global/Alerts.js
[0]  @ ./src/index.js
[0]  @ multi webpack-hot-middleware/client?reload=true ./src/index.js
[0] 
[0] WARNING in ../shared/node_modules/iota.lib.js/lib/utils/makeRequest.js 10:16-46
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ../shared/node_modules/iota.lib.js/lib/iota.js
[0]  @ ../shared/libs/iota/index.js
[0]  @ ./src/index.js
[0]  @ multi webpack-hot-middleware/client?reload=true ./src/index.js
[0] Child html-webpack-plugin for "index.html":
[0]          Asset      Size  Chunks  Chunk Names
[0]     index.html  1.41 MiB       0  
[0]     Entrypoint undefined = index.html
[0]     [./node_modules/html-webpack-plugin/lib/loader.js!./webpack.config/index.html] 509 bytes {0} [built]
[0]     [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
[0]     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
[0]     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
[0] ℹ ｢wdm｣: Compiled with warnings.

```

**Comment by KnockKnockNe0** [comment]
I got the same issue on Debian 9.6 (stretch) and Ubuntu 16.04 (xenial)
trinity-desktop-0.4.6.AppImage complains about missing dependencies
But both libsecret and gnome-keyring are installed:
libsecret-1-0 libsecret-1-dev libsecret-common libsecret-tools gnome-keyring

**Comment by KnockKnockNe0** [comment]
"Missing security dependencies" is displayed together with this:

```
[0] WARNING in ../shared/node_modules/iota.lib.js/lib/utils/makeRequest.js 10:16-46
[0] Critical dependency: the request of a dependency is an expression
[0]  @ ../shared/node_modules/iota.lib.js/lib/utils/utils.js
[0]  @ ../shared/node_modules/iota.lib.js/lib/iota.js
[0]  @ ../shared/libs/iota/index.js
[0]  @ ./src/index.js
[0]  @ multi webpack-hot-middleware/client?reload=true ./src/index.js
```
Sounds... critical to me

The line is:
`var request = pretendingNotToRequire(module).XMLHttpRequest;`

And then i get this:

```
.../sr…ity-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure                                 
    protocols.This exposes users of this app to unnecessary security risks.
        Consider loading the following resources over HTTPS or FTPS.
         - http://localhost:1074/css/main.css
         - http://localhost:1074/bundle.js
         - http://localhost:1074/images/ee2a11b8.ttf
         - http://localhost:1074/images/774c05cc.ttf
         - http://localhost:1074/images/afd6582a.ttf
         - http://localhost:1074/images/5182da42.ttf
         - http://localhost:1074/images/0cdb648a.ttf

```
Just warnings but it doesn't work

**Comment by KnockKnockNe0** [comment]
What i found out is:
The module that uses libsecret/gnome-keyring is "keytar"
So i tested that:

```
$ mkdir keytest && cd keytest
$ npm install keytar
```

Create file: sectest.js
```
const keytar = require('keytar');
keytar.setPassword('test', 'foo', 'bar');
const secret = keytar.getPassword('test', 'foo');
secret.then((password) => { console.log("Password[" + password + "]"); });
```

```
$ node sectest.js
Password[bar]
```
So the keyring does work and keytar does work. 

The tool "seahorse" is a useful GUI for managing the keyring.

Any Ideas?

**Comment by KnockKnockNe0** [comment]
The iota.lib.js does work too
`$ npm install iota.lib.js`
```
var IOTA = require('iota.lib.js');

// Create IOTA instance with host and port as provider
var iota = new IOTA({
   'host': 'http://localhost',
   'port': 14265
});

// Create IOTA instance directly with provider
var iota = new IOTA({
   'provider': 'http://localhost:14265'
});

// now you can start using all of the functions
iota.api.getNodeInfo(function(error, success) {
   if (error) {
      console.error(error);
   } else {
      console.log(success);
   }
});

// you can also get the version
console.log(iota.version);

```
```

$ node testiota.js
0.5.1
Error: Invalid Response: Error: connect ECONNREFUSED 127.0.0.1:14265

```

When i got a ncat listening on the port:
```

$ ncat -l -p 14265
POST / HTTP/1.1
User-Agent: node-XMLHttpRequest
Accept: */*
Content-Type: application/json
X-IOTA-API-Version: 1
Host: localhost:14265
Content-Length: 25
Connection: close

{"command":"getNodeInfo"}

```

**Comment by rajivshah3** [comment]
> Just warnings but it doesn't work

@KnockKnockNe0 once you do `npm run start` and see `compiled with warnings`, are you reloading the page? Sometimes it won't reload by itself and shows a white/blue screen

**Comment by KnockKnockNe0** [comment]
> > Just warnings but it doesn't work
> 
> @KnockKnockNe0 once you do `npm run start` and see `compiled with warnings`, are you reloading the page? Sometimes it won't reload by itself and shows a white/blue screen

I just get the Electron window with blue bg and white text "Missing security dependencies [...] libsecret missing [...]"
How would i reload that page? F5? (Didn't do anything)

**Comment by KnockKnockNe0** [comment]
I'm not sure why, but now i get a different error **"Cannot connect to Secret Service API"**
I located that msg in **"trinity-wallet/src/desktop/src/ui/global/FatalError.js"**
Changed line 21 to `<h1>Cannot connect to Secret Service API {error}</h1>`
This shows me the actual error: **Unknown or unsupported transport “disabled” for address “disabled:”**

**Comment by KnockKnockNe0** [comment]
Seems that that error message is depending on the locale setting
```
export LC_ALL=de_DE.UTF-8
The text in Electron is: "Missing security dependencies"

export LC_ALL=C
The text in Electron is: "Cannot connect to Secret Service API"

```

**Comment by rajivshah3** [comment]
Is anyone able to reproduce this issue in the latest build?

**Comment by KnockKnockNe0** [comment]
Version 0.5.0 does work for me with Ubuntu 16.04 (Xenial) \o/

**Comment by rajivshah3** [comment]
Great!

If anyone else is still running into issues, please leave a comment here and I'll reopen the issue
