### ISSUE TITLE
trinity-desktop-0.4.3.AppImage does not start on linux

### ISSUE THREAD

**Issue by olazpreton** [iotaledger/trinity-wallet#665]
### Bug description

trinity-desktop-0.4.3.AppImage does not start

### Environment Specs

What device are you running Trinity on?
- OS version: Linux Mint 19 "Tara" - Cinnamon (64-bit)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 
trinity-desktop-0.4.3.AppImage

### Steps To Reproduce
1. removed .config/Trinity
2. run appimage

### Expected behaviour
Trinity should start

### Actual behaviour
Trinity does not start

### Errors
content in Settings file:
{}

### Am I planning to do it myself with a PR?
No.

**Comment by miili** [comment]
Same here, neither pre-build `.AppImage` nor locally built.

```
$> ./trinity-desktop                                                                                                                                                Thu 15:06
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'ignoreProxy' of null
    at Object.<anonymous> (/home/marius/src/trinity-wallet/src/desktop/out/linux-unpacked/resources/app.asar/main.js:82:14)
    at Object.<anonymous> (/home/marius/src/trinity-wallet/src/desktop/out/linux-unpacked/resources/app.asar/main.js:482:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (/home/marius/src/trinity-wallet/src/desktop/out/linux-unpacked/resources/electron.asar/browser/init.js:189:8)
    at Object.<anonymous> (/home/marius/src/trinity-wallet/src/desktop/out/linux-unpacked/resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
```
